### ISSUE TITLE
Need README.md

### ISSUE THREAD

**Issue by varghs** [xXH4CKST3RXx/My-Stock-Predictor#1]
I need a README for this repository to explain it better. This repository is for a simple, basic stock predictor made with brain.js. The README doesn't have to be huge, it just has to explain the project. It should also explain how I am open to contributions.

**Comment by 110Percent** [comment]
I've submitted a [pull request](https://github.com/xXH4CKST3RXx/My-Stock-Predictor/pull/2) with a readme. Would this work for you, and what can I add to make it better?

**Comment by varghs** [comment]
This is great. Thanks.
